language: node_js
before_script: "./node_modules/.bin/cake test-setup"
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
    - "irc.freenode.org#docpad-dev"
  email:
    recipients:
      - travisci@bevry.me